### ISSUE TITLE
Cut a new release with sensors in

### ISSUE THREAD

**Issue by peternewman** [mathertel/DmxSerial2#12]
All of this is missing from 1.2.0:
https://github.com/mathertel/DmxSerial2/compare/1.2.0...master

So could we have a new release please @mathertel . I guess #11 should possibly go in first? And #10 which is easy aside from needing testing.

**Comment by mathertel** [comment]
done.
Thanks for all your support.

**Comment by peternewman** [comment]
Thanks for doing this, no worries.
