### ISSUE TITLE
Build warning when Compler Warnings = All (Part 2)

### ISSUE THREAD

**Issue by g0uus** [mathertel/DmxSerial2#19]
If the Arduino Compiler Warnings option is set to YES, the following warning is generated -
```
C:\Users\grh\Google Drive\Arduino\libraries\DmxSerial2\src\DMXSerial2.cpp: In member function 'uint8_t DMXSerialClass2::readRelative(unsigned int)':

C:\Users\grh\Google Drive\Arduino\libraries\DmxSerial2\src\DMXSerial2.cpp:395:16: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]

   if ((channel >= 0) && (channel < _initData->footprint)) {

                ^
```
This occurs because channel is declared as unsigned int.

The fix is simply to change the statement to
```
   if (channel < _initData->footprint) {
```

**Comment by peternewman** [comment]
See the discussion here https://github.com/mathertel/DmxSerial2/issues/18#issuecomment-430237661

In this case you probably want to add a comment saying what the old test was and maybe why it's been removed.
